library(caTools)
library(e1071)
mydata<-read.csv(file="G:/datasets/diabetes.csv",header=TRUE, sep=",")
View(mydata)
dim(mydata)
range(mydata$Age)
range(mydata$BloodPressure)
mean(mydata$Age)
temp_field<-sample.split(mydata, SplitRatio = 0.7)
train<-subset(mydata,temp_field==TRUE)
View(train)
dim(train)
range(train$Pregnancies)
range(train$Glucose)
test<-subset(mydata,temp_field==FALSE)
View(test)
head(mydata)
head(train)
head(test)
tail(train)
tail(test)
my_model<-naiveBayes(as.factor(train$Outcome)~.,train)
my_model
View(my_model)
pred1<-predict(my_model,test[,-9])
pred1
pred1<-predict(my_model,test[,-9],type="raw")
pred1
pred1<-predict(my_model,test[,-9],type="class")
pred1
dim(test)
dim(train)
table(pred1,test$Outcome,dnn=c("actual","predicted"))
output<-cbind(test,pred1)
View(output)
dim(output)

