library(e1071)
library(caTools)
mydata<-read.csv(file="G:/datasets/tripdata.csv",header=TRUE,sep=",")
View(mydata)
dim(mydata)
subset_mydata <- mydata[,c(1,4,6,9)]
temp_field <- sample.split(subset_mydata,SplitRatio=0.9)
train <- subset(subset_mydata, temp_field==TRUE)
View(train)
test <- subset(subset_mydata, temp_field==FALSE)
View(test)
summary(train)
summary(test)
head(train)
head(test)

View(train)
tail(train)
tail(test)
dim(test)
dim(train)
library(rpart)
fit <- rpart(train$Member.type~.,data=train,method="class")
plot(fit)
text(fit)
pred<- predict(fit,newdata=test[,-4],type=("class"))
table(pred,test$Member.type,dnn=c("predicted","actual"))  
output <- cbind(test,pred)
View(output)
printcp(fit)
rpart(formula = train$Member.type ~ ., data = train, method = "class")
opt<- which.min(fit$cptable[,"xerror"])   
cp <- fit$cptable[opt,"CP"] 
plotcp(fit)
pruned_model<-prune(fit,cp)
plot(fit)
text(fit)
rpart_pruned_predict<- predict(pruned_model,test[,-4],type="class")
rpart_pruned_predict


